### ISSUE TITLE
DeserializeLargeBsonObject test wrong directory Visual Studio 2017/NUnit 3 Adaptor

### ISSUE THREAD

**Issue by JonHanna** [JamesNK/Newtonsoft.Json.Bson#1]
Working directory can be set to e.g. C:\WINDOWS\system32 depending on how Visual Studio was opened, leading to the wrong path being used in the test.

**Comment by JamesNK** [comment]
Thanks, I reported it a couple of days ago https://github.com/Microsoft/vstest/issues/504

**Comment by JonHanna** [comment]
Nunit changing the way working directory works with it may be responsible.

**Comment by JamesNK** [comment]
I'm not in a huge rush to get this fixed - it only effects test runs from inside VS - the command line passes. I'm going to wait to hear whether vstest is going to fix it in the framework or not.

**Comment by JamesNK** [comment]
The vstest team has told me that they're fixing this issue in VS2017 Update 1. I'm going to wait for their fix.
