### ISSUE TITLE
Update Newtsonsoft.Json nuget reference to v11.x

### ISSUE THREAD

**Issue by wouterroos** [JamesNK/Newtonsoft.Json.Bson#13]
Hi, 

Currently I get a compiler warning when using the latest version Newtonsoft.Json.Bson because it has a dependency to v10.x of Newtonsoft.Json and I have another Nuget package (MassTransit) in the same project that requires v11.x of Newtonsoft.Json. 

When I run my solution I don't seem to have any issues so I the breaking changes in v11 of Newtonsoft.Json does not seem to impact Newtonsoft.Json.Bson. This would mean that, unless I'm missing something, this issue can be fixed with a minor/revision version bump Newtonsoft.Json.Bson in which the NuGet reference to Newtonsoft.Json will be updated to v11.x.

Thanks in advance,

Regards,
Wouter Roos

**Comment by monty241** [comment]
Same issue. We have switched to 11.x, but during specific steps we get an error of the assembly loader because NewtonSoft JSON 10.0 can not be loaded.

**Comment by JamesNK** [comment]
You need to add a binding redirect.

**Comment by monty241** [comment]
Yes, that might work too. Newton soft Json does not follow semversion in that a major version bumped doesn’t indicate a breaking change?

**Comment by JamesNK** [comment]
It does. Just because there is a breaking change doesn't mean you are broken.

**Comment by monty241** [comment]
My physician will be happy :-)

**Comment by JamesNK** [comment]
Likely in the next couple of weeks. But there is nothing stopping you using them together today with a binding redirect.
