### ISSUE TITLE
BsonDataReader multiple content with FileStream doesn't work

### ISSUE THREAD

**Issue by Marfusios** [JamesNK/Newtonsoft.Json.Bson#23]
Hello, 

I'm trying to store a large amount of data as binary JSON and later load them one by one. 
But it's not working with `FileStream`, according to [unit tests](https://github.com/JamesNK/Newtonsoft.Json.Bson/blob/master/Src/Newtonsoft.Json.Bson.Tests/BsonDataReaderTests.cs#L78) it works correctly with `MemoryStream`. 

Example: 
```csharp
class MyClass
{
    public string Msg { get; set; }
    public int Year { get; set; }
}

public static void Test()
{
    var obj1 = new MyClass { Msg = "1", Year = 2018 };
    var obj2 = new MyClass { Msg = "2", Year = 2019 };

    var fsWrite = new FileStream("my_file", FileMode.Append);
    var writer = new BsonDataWriter(fsWrite);
    using (writer)
    {
        var serializer = new JsonSerializer();
        serializer.Serialize(writer, obj1);
        serializer.Serialize(writer, obj2);
    }


    var fsRead = new FileStream("my_file", FileMode.Open);
    var reader = new BsonDataReader(fsRead)
    {
        SupportMultipleContent = true
    };
    using (reader)
    {
        var serializer = new JsonSerializer();

        while (reader.Read())
        {
            var deserialized = serializer.Deserialize<MyClass>(reader);
            // called only once and deserialized == obj1
        }
    }
}
```

Did I miss something? 

**UPDATE**

I've tried code from [unit test](https://github.com/JamesNK/Newtonsoft.Json.Bson/blob/master/Src/Newtonsoft.Json.Bson.Tests/BsonDataReaderTests.cs#L78) (with `MemoryStream`) and it also doesn't work (second object `tst2A` is null). 

I run the code inside console application and `<TargetFramework>netcoreapp2.1</TargetFramework>`. 
Newtonsoft.Json.Bson: 1.0.1
Newtonsoft.Json: 11.0.2

**UPDATE 2**

It's **working** with prerelease version `1.0.2-beta1` !

**Comment by JamesNK** [comment]
Yeah, it is fixed in the next version. A final version will be released in the next month.
