### ISSUE TITLE
Security Issue because of  < 13.0.1 

### ISSUE THREAD

**Issue by iamrahul127** [JamesNK/Newtonsoft.Json.Bson#35]
Hi,
Our SCA tool is reporting high severity security issue as **Newtonsoft.Json.Bson** is referring to **Newtonsoft.Json** version < _13.0.1_. We have noticed that you have fixed the issue under https://github.com/JamesNK/Newtonsoft.Json/issues/2535 for **Newtonsoft.Json**.

Could you please let us know if you have plan to upgrade **Newtonsoft.Json** used by **Newtonsoft.Json.Bson** to  _13.0.1_?

**Comment by JamesNK** [comment]
> Could you please let us know if you have plan to upgrade Newtonsoft.Json used by Newtonsoft.Json.Bson to 13.0.1?

Yes. No date.

> Our SCA tool is reporting high severity security issue as Newtonsoft.Json.Bson is referring to Newtonsoft.Json version < 13.0.1.

Newtonsoft.Json.Bson has a reference to the minimum version required. There is nothing stopping an app from referencing Newtonsoft.Json 13.0.1 itself.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json.Bson/issues/35
