### ISSUE TITLE
Compatibility for Netonsoft.Json 13?

### ISSUE THREAD

**Issue by Arugin** [JamesNK/Newtonsoft.Json.Bson#40]
Is it planned or this package is obosolete and abandoned? If not, maybe it is time to mark this repository as not maintained anymore?

**Comment by suuyashgupta** [comment]
@JamesNK Is there a timeline when 1.0.3 version would be released?

**Comment by JamesNK** [comment]
See https://github.com/JamesNK/Newtonsoft.Json.Bson/issues/42#issuecomment-1707803383

**Comment by JamesNK** [comment]
Done: https://www.nuget.org/packages/Newtonsoft.Json.Bson/1.0.3
